# Generated by Django 3.1.7 on 2021-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(to='core.ResourceCategory'),
        ),
    ]
