# Generated by Django 3.2.2 on 2021-05-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_githubgist_embed_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('embed_code', models.TextField(verbose_name='Code Snippet Embed Code with Script Tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_snippet_cb', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('category', models.ManyToManyField(to='core.ResourceCategory', verbose_name='Resource Category')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_snippet_ub', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'verbose_name_plural': 'Code Snippets',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.DeleteModel(
            name='GitHubGist',
        ),
    ]
