# Generated by Django 3.2.2 on 2021-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210513_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(verbose_name='Your Code Snippet'),
        ),
    ]
