# Generated by Django 3.2.2 on 2021-05-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210513_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecategory',
            name='is_programming_language',
        ),
    ]
