# Generated by Django 3.1.7 on 2021-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210306_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
