# Generated by Django 3.1.7 on 2021-03-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_resource_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_cb', to=settings.AUTH_USER_MODEL),
        ),
    ]
