# Generated by Django 3.1.7 on 2021-03-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactus'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='resource',
        #     name='description',
        # ),
        # migrations.RemoveField(
        #     model_name='resource',
        #     name='thumbnail',
        # ),
    ]
