# Generated by Django 3.1.7 on 2021-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactus'),
        ('core', '0013_auto_20210314_1810'),
    ]

    operations = [
    ]
