# Generated by Django 3.2.2 on 2021-05-09 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20210507_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=140, verbose_name='Your Full Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Write somethig to us...'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_cb', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(to='core.ResourceCategory', verbose_name='Resource Category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_ub', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Resource Link'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='GitHubGist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('embed_url', models.URLField(verbose_name='Link to the GitHub Gist')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='githubgist_cb', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='githubgist_ub', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'GitHub Gist',
                'verbose_name_plural': 'GitHub Gists',
                'ordering': ['-updated_on'],
            },
        ),
    ]
