# Generated by Django 3.1.7 on 2021-03-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210325_1202'),
        ('core', '0015_auto_20210326_1238'),
    ]

    operations = [
    ]
