# Generated by Django 3.2.2 on 2021-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210509_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubgist',
            old_name='embed_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='githubgist',
            name='category',
            field=models.ManyToManyField(to='core.ResourceCategory', verbose_name='Resource Category'),
        ),
    ]
