# Generated by Django 3.2.2 on 2021-05-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20210509_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubgist',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='github_gist_cb', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='githubgist',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='github_gist_ub', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
