# Generated by Django 3.1.7 on 2021-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210301_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='slug',
            field=models.SlugField(default='ksjd', editable=False),
            preserve_default=False,
        ),
    ]
