# Generated by Django 3.1.7 on 2021-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210303_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-updated_on'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
