# Generated by Django 3.2.2 on 2021-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20210326_1240'),
        ('core', '0020_auto_20210510_2209'),
    ]

    operations = [
    ]
