import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DevJunction</title>
        <meta name="description" content="Generated by DevJunction" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Something</main>

      <footer>Footer</footer>
    </div>
  );
}
