import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DevJunction</title>
        <meta name="description" content="Generated by DevJunction" />
      </Head>

      <main>Something</main>
    </div>
  );
}
